version: "3.8"
services:
  windows:
    image: dockurr/windows:latest
    container_name: windows11
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      VERSION: "11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "513G"
      USERNAME: "HappyGhastQwQ"
      PASSWORD: "kiubby"
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
      - "2222:22"
    volumes:
      - ./windows:/storage
      - ./oem:/oem
    restart: always
    stop_grace_period: 2m
